### ISSUE TITLE
allaymc目前的问题

### ISSUE THREAD

**Issue by Avrilzion** [AllayMC/Allay#232]
服务器官网下载等多个按钮不起作用无法正常跳转[服务器官网](https://www.allaymc.org/#/)
- 你们的服务端不提示服务端所支持的minecraft游戏版本
- 服务端不论是自己构建\运行，还是从GitHub Actions下载运行都存在下面问题
- 你们的服务端正常启动了但网络服务器不正常延迟 4448ms

![20240515211518](https://github.com/AllayMC/Allay/assets/62799045/b19ca55a-529a-4706-9422-b2b533e5b675)
- 还有server-settings.yml文件中没有提示可以更换其他语言的注释

**Comment by IWareQ** [comment]
Thank you for your feedback!

In the near future, we’ll fix the functionality of the buttons on the official website, add support for Minecraft game versions, and include comments in the server-settings.yml file regarding language options.

The time indicated at the end is calculated from the server's startup, not the network. Auxiliary links:
Start time: [link](https://github.com/AllayMC/Allay/blob/6a3d5fca1ef99a8f2365e16fab993a29c573c729/Allay-Server/src/main/java/org/allaymc/server/Allay.java#L74)
End time: [link](https://github.com/AllayMC/Allay/blob/6a3d5fca1ef99a8f2365e16fab993a29c573c729/Allay-Server/src/main/java/org/allaymc/server/AllayServer.java#L192)
Output of the difference between start and end: [link](https://github.com/AllayMC/Allay/blob/6a3d5fca1ef99a8f2365e16fab993a29c573c729/Allay-Server/src/main/java/org/allaymc/server/AllayServer.java#L193)

**Comment by Avrilzion** [comment]
现在还有个问题服务端无法正常启动，连接不到本地服务器

**Comment by IWareQ** [comment]
> 现在还有个问题服务端可以启动，但mc连接不到本地服务器，我不知道是哪里出了问题

Windows UWP apps have some restrictions on what they are allowed to do by default. Unfortunately, this includes connecting to things on localhost.

To lift this restriction from Minecraft, launch Windows PowerShell as an administrator and run the following:

```
CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"
```

**Comment by Avrilzion** [comment]
目前来说没有太大问题，但希望将多维度功能提上开发路线图，目前下界维度，末地维度，下届\末地传送框架都无法激活，如果可以的话在添加一个 多维度传送通用框架api 使其mod开发者可以给添加其他维度并调用传送门api 进行维度相互传送，并在更新一下mod编写教程

**Comment by smartcmd** [comment]
> 目前来说没有太大问题，但希望将多维度功能提上开发路线图，目前下界维度，末地维度，下届\末地传送框架都无法激活，如果可以的话在添加一个 多维度传送通用框架api 使其mod开发者可以给添加其他维度并调用传送门api 进行维度相互传送，并在更新一下mod编写教程

多维度已经实现了，看源码
