### ISSUE TITLE
bug: health bar keeps flashing

### ISSUE THREAD

**Issue by smartcmd** [AllayMC/Allay#309]
https://github.com/user-attachments/assets/dfe8e3d8-7d57-4303-adfc-55e199008837

**Comment by IWareQ** [comment]
This regeneration effect behavior is not a bug

**Comment by smartcmd** [comment]
It flash much quicker than vanilla?

**Comment by IWareQ** [comment]
we can't influence this in any way, this is a client animation, I compared it with the server - they are the same

**Comment by smartcmd** [comment]
okk
