### ISSUE TITLE
feat: allow 3rd plugin loader

### ISSUE THREAD

**Issue by smartcmd** [AllayMC/Allay#335]

**Comment by wu-vincent** [comment]
🥹

**Comment by smartcmd** [comment]
> 🥹

🥹

**Comment by didntpot** [comment]
> > 🥹
> 
> 🥹

🥹

**Comment by sleepingmagg** [comment]
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥹

**Comment by smartcmd** [comment]
> > > > 🥹
> > > 
> > > 
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥹

**Comment by Lintha437** [comment]
> > > > > 🥹
> > > > 
> > > > 
> > > > 🥹
> > > 
> > > 
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥹

**Comment by Buddelbubi** [comment]
> > > > > > 🥹
> > > > > 
> > > > > 
> > > > > 🥹
> > > > 
> > > > 
> > > > 🥹
> > > 
> > > 
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥹

**Comment by harry-xi** [comment]
> > > > > > > 🥹
> > > > > > 
> > > > > > 
> > > > > > 🥹
> > > > > 
> > > > > 
> > > > > 🥹
> > > > 
> > > > 
> > > > 🥹
> > > 
> > > 
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥹

**Comment by Cdm2883** [comment]
🥹

**Comment by Buddelbubi** [comment]
> 🥹

🥹

**Comment by smartcmd** [comment]
> > 🥹
> 
> 🥹

🥹

**Comment by heyhey123-git** [comment]
🤗

**Comment by Cdm2883** [comment]
> > > 🥹
> > 
> > 
> > 🥹
> 
> 🥹

🥺🥺🥺

**Comment by Cdm2883** [comment]
Isn't it possible to support 3rd party plugin loaders 🤔 Why is there this issue 🤔

**Comment by smartcmd** [comment]
> Isn't it possible to support 3rd party plugin loaders 🤔 Why is there this issue 🤔

Because when a plugin is loaded, the plugin manager has been freezed and 3rd plugin can't register their custom plugin loader
