### ISSUE TITLE
feat: introduce the new system to let plugin use block & item id safely

### ISSUE THREAD

**Issue by smartcmd** [AllayMC/Allay#395]
The content in `BlockId.java`, `BlockPropertyTypes.java`, `ItemId.java` will be changed when updating to the next protocol version. If the plugin uses these classes, it may be broken in the future.

Our origin design is to let plugin authors adapt the changes manually. However, thanks to [StateUpdater](https://github.com/AllayMC/StateUpdater) by IWareQ, We now have a new idea for this problem.

This idea has been used in terra plugin, which allows the terra plugin to automatically adapt to the new mcbe version.

**Comment by IWareQ** [comment]
:>

**Comment by smartcmd** [comment]
> :>

:>
