### ISSUE TITLE
docs: collect community allay plugin templates such as kotlin

### ISSUE THREAD

**Issue by Cdm2883** [AllayMC/Allay#424]
I believe that accepting community templates offers more advantages than disadvantages for the following reasons:

1. **Consistency with Language-Specific Naming Conventions**: If we only accept repositories from the AllayMC organization, they must follow the project's naming convention, which requires CamelCase. However, this may conflict with the naming conventions of the programming language used in the template (e.g., material 1), leading to an inconsistent experience for developers who use that language.

2. **Fostering Community Engagement**: Documentation often serves as the entry point for a developer's first contribution to a project. Seeing immediate support for their preferred language in the documentation enhances a developer's enthusiasm and sense of belonging. If such support is missing, developers may be more motivated to contribute by adding their favorite language template and submitting it for inclusion in the community templates (e.g., material 2).

3. **Promoting Template Uniformity**: Offering available templates in the documentation encourages the use of standardized templates, making it easier for developers to start building their ideas. This contributes to greater unity within the community, avoiding the fragmentation that occurs when developers feel compelled to create new templates from scratch due to the absence of support for their chosen language.

### 1. In Kotlin projects with long names, the dash naming convention is often used.

| [GitHub Search page](https://github.com/search?q=language%3AKotlin+&type=repositories&p=1) | [JetBrains' Kotlin project names](https://github.com/orgs/JetBrains/repositories) |
|  ----  | ----  |
| ![1-1](https://github.com/user-attachments/assets/417e9d48-663a-4c76-931e-700f8b77f5f7) | ![image](https://github.com/user-attachments/assets/1cd1445b-0342-40ed-8056-382ce59b0e84) |

### 2. Many open-source projects offer channels for accepting derivative community projects.

|  [From the official Kotlin kotlinx.serialization library](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md)  | [The homepage of the Mirai official website documentation](https://docs.mirai.mamoe.net) |
|  ----  | ----  |
| ![2-1](https://github.com/user-attachments/assets/9650252d-cd1e-4be2-8870-7824f9991c35)  | ![2-2](https://github.com/user-attachments/assets/a8137e77-2860-44e4-b00d-1f0627a14dd6) |

**Comment by smartcmd** [comment]
Already being done in https://github.com/AllayMC/Allay/commit/f58fd9d71b24694ea97897d534b5698808d0efda
