### ISSUE TITLE
bug: Task Exception when connect with unsupported version

### ISSUE THREAD

**Issue by kanisonpoon** [AllayMC/Allay#509]
![image](https://github.com/user-attachments/assets/a26dff91-690b-4953-979b-c9f5b071fc24)
How to reproduce 
join with unsupported version
wait and you will get the Task Exception

**Comment by IWareQ** [comment]
Cannot reproduce

![image](https://github.com/user-attachments/assets/23f28669-5d64-4dcc-a9d2-173fdb9ec057)

**Comment by kanisonpoon** [comment]
it not immediately happened you have to wait like a minute

**Comment by smartcmd** [comment]
Got it, Will fix it later. Thanks

**Comment by smartcmd** [comment]
Fixed
