### ISSUE TITLE
Bug: Server think you are still in

### ISSUE THREAD

**Issue by kanisonpoon** [AllayMC/Allay#513]
just join and rejoin the server (have no plugin)
![image](https://github.com/user-attachments/assets/68504fe9-75ef-4eb2-a447-56ef3af3198e)
when disconnected the motd is showing i still in the server
![image](https://github.com/user-attachments/assets/c1524767-6931-472a-8310-ec6edef3712d)

**Comment by IWareQ** [comment]
fixed in https://github.com/AllayMC/Allay/commit/09f9b2e20df40542edf1050f95a0fe9f2f08ef62

**Comment by kanisonpoon** [comment]
yeah this was fixed
