### ISSUE TITLE
Allay 0.1.0 的部分问题（挖掘、放置）

### ISSUE THREAD

**Issue by virgil698** [AllayMC/Allay#529]
第一个问题：出生点半截入土

![94555f54585482ef60974b32d98817ac](https://github.com/user-attachments/assets/70ce63c4-08d6-42e5-b868-cd56244dcbb8)

第二个问题：斜放方块放不出来、放快了会出现吞方块的问题、手有点长（EndStone群聊里有测试视频）

第三个问题：跑跳搭方块不能斜着搭

而且Allay的放方块的动作也很容易受到干扰，干扰到了直接不放了

不确定的问题：没加速前跑酷能跳两格远，加速了能跳三格

建议：看看能不能还原Java版那个横扫，一次发力多个玩家受到伤害，但重击的伤害要比原来的低

**Comment by smartcmd** [comment]
Thank you for reaching out. We can only provide support in English. Could you update your issue so we can better assist you?

I'll close it for now but feel free to reopen it once it's been updated.
